using Windows.Graphics.Display;
using Windows.UI.ViewManagement;

// DO NOT EDIT THIS FILE! IT HAS BEEN AUTO GENERATED!

namespace FlaxEngine
{{
    internal static class InitUWP
    {{
        public static void SetupDisplay()
        {{
			DisplayInformation.AutoRotationPreferences = {0};
			ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.{1};
        }}
    }}
}}
